apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-reaper
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: slaclab/grid-security-files:latest
        command: cp /grid-certificates/* /out/
        volumeMounts:
        - name: ca-volume
          moutnPath: /out/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}
