---
# Source: rucio-server/templates/auth_deployment.yaml
apiVersion: v1
kind: Secret
metadata:
  name: usdf-rucio-server-auth.config.yaml
  labels:
    app: rucio-server-auth
    chart: "rucio-server"
    release: "usdf"
    heritage: "Helm"
type: Opaque
data:
  rucio.config.common.json: "ewogICJhcGkiOiB7CiAgICAiZW5kcG9pbnRzIjogImF1dGgsYWNjb3VudGxpbWl0cyxhY2NvdW50cyxjb25maWcsY3JlZGVudGlhbHMsZGlkcyxleHBvcnQsaGVhcnRiZWF0cyxpZGVudGl0aWVzLGltcG9ydCxsaWZldGltZV9leGNlcHRpb25zLGxvY2tzLG1ldGEscGluZyxyZWRpcmVjdCxyZXBsaWNhcyxyZXF1ZXN0cyxyc2VzLHJ1bGVzLHNjb3BlcyxzdWJzY3JpcHRpb25zIgogIH0KfQ=="
---
# Source: rucio-server/templates/deployment.yaml
apiVersion: v1
kind: Secret
metadata:
  name: usdf-rucio-server.config.yaml
  labels:
    app: rucio-server
    chart: "rucio-server"
    release: "usdf"
    heritage: "Helm"
type: Opaque
data:
  rucio.config.common.json: "ewogICJhcGkiOiB7CiAgICAiZW5kcG9pbnRzIjogImF1dGgsYWNjb3VudGxpbWl0cyxhY2NvdW50cyxjb25maWcsY3JlZGVudGlhbHMsZGlkcyxleHBvcnQsaGVhcnRiZWF0cyxpZGVudGl0aWVzLGltcG9ydCxsaWZldGltZV9leGNlcHRpb25zLGxvY2tzLG1ldGEscGluZyxyZWRpcmVjdCxyZXBsaWNhcyxyZXF1ZXN0cyxyc2VzLHJ1bGVzLHNjb3BlcyxzdWJzY3JpcHRpb25zIgogIH0KfQ=="
---
# Source: rucio-server/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: usdf-rucio-server.cfg
  labels:
    app: rucio-server
    chart: "rucio-server-1.29.1"
    release: "usdf"
    heritage: "Helm"
type: Opaque
data:
  enable_status: "VHJ1ZQ=="
  keep_alive: "T24="
  keep_alive_timeout: "NQ=="
  legacy_dn: "VHJ1ZQ=="
  max_connections_per_child: "MjA0OA=="
  max_keep_alive_requests: "MTI4"
  max_request_workers: "MTI4MA=="
  max_spare_threads: "NTEy"
  min_spare_threads: "MjU2"
  mpm_mode: "ZXZlbnQ="
  server_limit: "MTA="
  start_servers: "NA=="
  thread_limit: "MTI4"
  threads_per_child: "MTI4"
---
# Source: rucio-server/templates/auth_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: usdf-rucio-server-auth
  labels:
    app: rucio-server-auth
    chart: rucio-server-1.29.1
    release: usdf
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http-rucio-server-auth
  selector:
    app: rucio-server-auth
    release: usdf
---
# Source: rucio-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: usdf-rucio-server
  labels:
    app: rucio-server
    chart: rucio-server-1.29.1
    release: usdf
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http-rucio-server
  selector:
    app: rucio-server
    release: usdf
---
# Source: rucio-server/templates/auth_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-rucio-server-auth
  labels:
    app: rucio-server-auth
    chart: rucio-server-1.29.1
    release: usdf
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-server-auth
      release: usdf
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rucio-server-auth
        release: usdf
      annotations:
        checksum/config: a3e76fd28270378eaceeddb256acbe109eb39c3a
    spec:
      volumes:
      - name: config
        secret:
          secretName: usdf-rucio-server-auth.config.yaml
      - name: httpdlog
        emptyDir: {}
      containers:
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
        - name: rucio-server-auth
          image: "rucio/rucio-server:release-1.29.4"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 700m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /opt/rucio/etc/rucio.config.common.json
              subPath: rucio.config.common.json
            - name: httpdlog
              mountPath: /var/log/httpd
          env:
            - name: RUCIO_HTTPD_ENABLE_STATUS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: enable_status
            - name: RUCIO_HTTPD_KEEP_ALIVE
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: keep_alive
            - name: RUCIO_HTTPD_KEEP_ALIVE_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: keep_alive_timeout
            - name: RUCIO_HTTPD_LEGACY_DN
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: legacy_dn
            - name: RUCIO_HTTPD_MAX_CONNECTIONS_PER_CHILD
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_connections_per_child
            - name: RUCIO_HTTPD_MAX_KEEP_ALIVE_REQUESTS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_keep_alive_requests
            - name: RUCIO_HTTPD_MAX_REQUEST_WORKERS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_request_workers
            - name: RUCIO_HTTPD_MAX_SPARE_THREADS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_spare_threads
            - name: RUCIO_HTTPD_MIN_SPARE_THREADS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: min_spare_threads
            - name: RUCIO_HTTPD_MPM_MODE
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: mpm_mode
            - name: RUCIO_HTTPD_SERVER_LIMIT
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: server_limit
            - name: RUCIO_HTTPD_START_SERVERS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: start_servers
            - name: RUCIO_HTTPD_THREAD_LIMIT
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: thread_limit
            - name: RUCIO_HTTPD_THREADS_PER_CHILD
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: threads_per_child
            - name: RUCIO_ENABLE_SSL
              value: "False"
            - name: RUCIO_SERVER_TYPE
              value: "flask"
            - name: RUCIO_CFG_API_ENDPOINTS
              value: "auth,ping"
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/rucio.config.common.json"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_WSGI_DAEMON_PROCESSES
              value: "4"
            - name: RUCIO_WSGI_DAEMON_THREADS
              value: "4"
---
# Source: rucio-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-rucio-server
  labels:
    app: rucio-server
    chart: rucio-server-1.29.1
    release: usdf
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-server
      release: usdf
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rucio-server
        release: usdf
      annotations:
        checksum/config: a3e76fd28270378eaceeddb256acbe109eb39c3a
    spec:
      volumes:
      - name: config
        secret:
          secretName: usdf-rucio-server.config.yaml
      - name: httpdlog
        emptyDir: {}
      containers:
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
          resources:
            limits:
              cpu: 30m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 20Mi
        - name: rucio-server
          image: "rucio/rucio-server:release-1.29.4"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 700m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
          - name: config
            mountPath: /opt/rucio/etc/rucio.config.common.json
            subPath: rucio.config.common.json
          - name: httpdlog
            mountPath: /var/log/httpd
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: RUCIO_HTTPD_ENABLE_STATUS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: enable_status
            - name: RUCIO_HTTPD_KEEP_ALIVE
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: keep_alive
            - name: RUCIO_HTTPD_KEEP_ALIVE_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: keep_alive_timeout
            - name: RUCIO_HTTPD_LEGACY_DN
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: legacy_dn
            - name: RUCIO_HTTPD_MAX_CONNECTIONS_PER_CHILD
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_connections_per_child
            - name: RUCIO_HTTPD_MAX_KEEP_ALIVE_REQUESTS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_keep_alive_requests
            - name: RUCIO_HTTPD_MAX_REQUEST_WORKERS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_request_workers
            - name: RUCIO_HTTPD_MAX_SPARE_THREADS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: max_spare_threads
            - name: RUCIO_HTTPD_MIN_SPARE_THREADS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: min_spare_threads
            - name: RUCIO_HTTPD_MPM_MODE
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: mpm_mode
            - name: RUCIO_HTTPD_SERVER_LIMIT
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: server_limit
            - name: RUCIO_HTTPD_START_SERVERS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: start_servers
            - name: RUCIO_HTTPD_THREAD_LIMIT
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: thread_limit
            - name: RUCIO_HTTPD_THREADS_PER_CHILD
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-server.cfg
                  key: threads_per_child
            - name: RUCIO_ENABLE_SSL
              value: "False"
            - name: RUCIO_SERVER_TYPE
              value: "flask"
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/rucio.config.common.json"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_WSGI_DAEMON_PROCESSES
              value: "4"
            - name: RUCIO_WSGI_DAEMON_THREADS
              value: "4"
---
# Source: rucio-server/templates/auth_ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usdf-rucio-server-auth
  labels:
    app: rucio-server-auth
    chart: rucio-server-1.29.1
    release: usdf
    heritage: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/frontend-entry-points: http
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - rubin-rucio-dev.slac.stanford.edu
      secretName: rucio-server.tls-secret
  rules:
    - host: rubin-rucio-dev.slac.stanford.edu
      http:
        paths:
          - path: /auth
            backend:
              service:
                name: usdf-rucio-server-auth
                port:
                  number: 80
            pathType: Prefix
---
# Source: rucio-server/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usdf-rucio-server
  labels:
    app: rucio-server
    chart: rucio-server-1.29.1
    release: usdf
    heritage: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/frontend-entry-points: http
spec:
  tls:
    - hosts:
        - rubin-rucio-dev.slac.stanford.edu
      secretName: rucio-server.tls-secret
  rules:
    - host: 'rubin-rucio-dev.slac.stanford.edu'
      http:
        paths:
          - path: /
            backend:
              service:
                name: usdf-rucio-server
                port:
                  number: 80
            pathType: Prefix
