apiVersion: v1
kind: Service
metadata:
  name: usdf-rucio-ui
spec:
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usdf-rucio-ui
spec:
  rules:
  - host: "usdf-rucio.slac.stanford.edu"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: usdf-rucio-ui
            port:
              name: https

