apiVersion: v1
kind: Pod
metadata:
  namespace: rucio
  name: rucio-db-upgrade
spec:
  containers:
  - name: rucio-db-upgrade
    image: rucio/rucio-init:latest
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: RUCIO_CFG_DATABASE_DEFAULT
      valueFrom:
        secretKeyRef:
          name: usdf-db-conn-str
          key: db-conn-str.txt