
resources:
- ns.yaml
# cnpg
- cnpg-rucio-database.yaml
- cnpg-rucio-pooler.yaml

### hmm... the endpoint doens't exist here for kustomize to do anythign abot it; add into Makefile?
#patchesStrategicMerge:
#- endpoints-patch.yaml

secretGenerator:
- name: usdf-rucio-dev-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

#nameSuffix: -dev
namespace: rucio-db
commonLabels:
  env: dev
  app: rucio
  namespace: rucio-db

#configMapGenerator:
#- name: telegraf-postgres
#  files:
#  - telegraf.conf
#  - postgresql_custom_data.conf 

