apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-automatix
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: docker.io/bjwhitefnal/grid-security-files:latest
        command:
        - cp
        - -rL
        - /grid-certificates/.
        - /out/
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-reaper
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: docker.io/bjwhitefnal/grid-security-files:latest
        command:
        - cp
        - -rL
        - /grid-certificates/.
        - /out/
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}
